// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr9-A8qZkPdZlEt2urvGoVdA98N5Povec',
    appId: '1:163490541050:web:83b15254c0315bd4f4c843',
    messagingSenderId: '163490541050',
    projectId: 'marker-indoor-nav',
    authDomain: 'marker-indoor-nav.firebaseapp.com',
    storageBucket: 'marker-indoor-nav.appspot.com',
    measurementId: 'G-8S9KQ1J8QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiX6CjwBwUtuuELZKhVhsA2z3O0qLc6x4',
    appId: '1:163490541050:android:96eaf1b96d35b85ef4c843',
    messagingSenderId: '163490541050',
    projectId: 'marker-indoor-nav',
    storageBucket: 'marker-indoor-nav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKmxsF8bNTLITKpONqlEQ4rsfjszDKGGs',
    appId: '1:163490541050:ios:ed21955af2a20df4f4c843',
    messagingSenderId: '163490541050',
    projectId: 'marker-indoor-nav',
    storageBucket: 'marker-indoor-nav.appspot.com',
    iosBundleId: 'com.example.markerIndoorNav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKmxsF8bNTLITKpONqlEQ4rsfjszDKGGs',
    appId: '1:163490541050:ios:0c613f9c4a0247e1f4c843',
    messagingSenderId: '163490541050',
    projectId: 'marker-indoor-nav',
    storageBucket: 'marker-indoor-nav.appspot.com',
    iosBundleId: 'com.example.markerIndoorNav.RunnerTests',
  );
}
